language: node_js
node_js:
  - "10"
directories:
  - node_modules
before_install:
  - sudo apt-get install -y sshpass
script:
  - yarn build
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh $BRANCH
  on:
    branch: master
after_success:
  - ./deploy.sh $BRANCH
notifications:
  slack:
    on_success: change
    on_failure: change
